version: '3.8'
networks:
  encuestapp-network:
    driver: bridge
services:
  encuestapp-microservicio-encuestas:
    image: encuestapp-microservicio-encuestas:v1
    depends_on:
      - microservicios-db
    container_name: encuestapp-microservicio-encuestas
    ports:
      - "3006:3001"
    build:
      context: ./microservicio-encuestas
      dockerfile: dockerfile
    networks:
      - encuestapp-network

  encuestapp-microservicio-login-register:
    image: encuestapp-microservicio-login-register:v1
    depends_on:
      - microservicios-db
    container_name: encuestapp-microservicio-login-register
    ports:
      - "3005:3000"
    build:
      context: ./microservicio-de-login-register
      dockerfile: dockerfile
    networks:
      - encuestapp-network


  microservicios-db:
    image: microservicios-db:v1
    command: --default-authentication-plugin=mysql_native_password
    container_name: microservicios-db
    environment:
      - MYSQL_DATABASE=encuestapphttp
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "30001:3306"
    build:
      context: ./microservicio-de-login-register/src/dataaccess/database-config
      dockerfile: dockerfile
    restart: always
    volumes:
    - ./microservicio-de-login-register/src/dataaccess/mysql-data:/var/lib/mysql
    networks:
     - encuestapp-network

  vue-app:
    image: encuestapp-vue-app:v1
    container_name: encuestapp-vue-app
    build:
      context: ./vue-front
      dockerfile: dockerfile
    ports:
      - "8080:80" # Puedes mapear el puerto 80 del contenedor al puerto que prefieras en tu máquina local
    networks:
      - encuestapp-network

volumes:
  mysql-data: