on: push
name: deploy

jobs:
  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: raptoverdad/encuestapp-microservicio-encuestas
            dockerfile: microservicio-encuestas/dockerfile
            context: ./microservicio-encuestas
          - image: raptoverdad/encuestapp-microservicio-de-login-register
            dockerfile: microservicio-de-login&register/dockerfile
            context: ./microservicio-de-login&register
          - image: raptoverdad/encuestapp-microservicio-encuestas-db
            dockerfile: microservicio-encuestas/dataaccess/database-config/dockerfile
            context: ./microservicio-encuestas/dataaccess/database-config
          - image: raptoverdad/encuestapp-microservicio-login-register-db
            dockerfile: microservicio-de-login&register/dataaccess/database-config/dockerfile
            context: ./microservicio-de-login&register/dataaccess/database-config
          - image: raptoverdad/encuestapp-vue-app
            dockerfile: vue-front/dockerfile
            context: ./vue-front
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

